services:
  mysql-database:
    container_name: dssba-mysql-db
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - /.src/data:/var/lib/mysql
    networks:
      - dssba-network

  grafana:
    container_name: grafana_dssba
    image: grafana/grafana

    ports:
      - "3000:3000"
    networks:
      - dssba-network
    restart: unless-stopped


  prometeus:
    container_name: prometheus_dssba
    image: prom/prometheus

    ports:
      - "9090:9090"
    networks:
      - dssba-network
    restart: unless-stopped
    volumes:
    - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml


networks:
  dssba-network:
    driver: bridge
