services:
  grafana:
    container_name: grafana
    image: grafana/grafana

    ports:
      - "3000:3000"
    networks:
      - grafana
    restart: unless-stopped


  prometeus:
    container_name: prometheus
    image: prom/prometheus

    ports:
      - "9090:9090"
    networks:
      - grafana
    restart: unless-stopped
    volumes:
    - C:/Users/lildk/Desktop/PRO/Labs/Java/DSSBA/DSSBA/DeanerySimpleSpringBootApp/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml


networks:
  grafana:
    driver: bridge
