services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:

    volumes:
      - grafana:/data/grafana
    ports:
      - "3000:3000"
    networks:
      - grafana
    restart: unless-stopped


  prometeus:
    container_name: prometheus
    image: prom/prometheus
    environment:

    volumes:
      - prometheus:/var/lib/pgadmin

    ports:
      - "9090:9090"
    networks:
      - grafana
    restart: unless-stopped

networks:
  grafana:
    driver: bridge

volumes:
  grafana:
  prometheus: